export enum GameTurn {
    PUT_SUBMARINE='STATE/00/PUT_SUBMARINE',
    PUT_DESTROYER='STATE/01/PUT_DESTROYER',
    PUT_BATTLESHIP='STATE/02/PUT_BATTLESHIP',
    WAITING_ANOTHER_PLAYER='STATE/03/WAITING_ANOTHER_PLAYER',
    START_GAME='STATE/04/START_GAME',
    TURN_PLAYER_1='STATE/05/TURN_PLAYER_1',
    TURN_PLAYER_2='STATE/06/TURN_PLAYER_2',
    END_GAME='STATE/07/END_GAME',
}
