export enum GameTurn {
    PUT_SHIPS='STATE/00/PUT_SHIPS',
    WAITING_ANOTHER_PLAYER='STATE/03/WAITING_ANOTHER_PLAYER',
    START_GAME='STATE/04/START_GAME',
    TURN_PLAYER_1='STATE/05/TURN_PLAYER_1',
    TURN_PLAYER_2='STATE/06/TURN_PLAYER_2',
    END_GAME='STATE/07/END_GAME',
}
